# Site settings
title: BigJackson Blog
SEOTitle: 大杰克森的博客 | BigJackson Blog
header-img: img/home-bg.jpg
email: tud8951@gmail.com
description: "这里是 @BigJackson大杰克森 的个人博客，与你一起发现更大的世界 | 要做一个有 swag 的程序员"
keyword: "大杰克森的博客, BigJackson Blog, 博客, 个人网站, 互联网, Web, JavaScript, React, React Native, 前端, 设计"
url: "https://bigjackson.us.kg" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: BigJackson
zhihu_username: BigJackson
github_username: BigJackson
twitter_username: BigJackson
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: BigJackson

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: bigjackson.us.kg

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "要做一个有 stem 的科技区主播 <br> React Team "
sidebar-avatar: https://bigjackson.us.kg/img/ROG-logo.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "Out81134", href: "https://space.bilibili.com/3493284294953144?spm_id_from=333.999.0.0" },
    { title: "姚亮008", href: "https://space.bilibili.com/357442724/?spm_id_from=333.999.0.0" },
    { title: "寄长风予歌", href: "https://space.bilibili.com/3494379251567353?spm_id_from=333.999.0.0" },
    { title: "百慕大椰子", href: "https://space.bilibili.com/3493138503043671/?spm_id_from=333.999.0.0" },
    { title: "残念幽游", href: "https://space.bilibili.com/3494366238738465?spm_id_from=333.999.0.0" },
    { title: "数码好物libra", href: "https://space.bilibili.com/138804066/?spm_id_from=333.999.0.0" },
    { title: "科技新观察-jeremie", href: "https://space.bilibili.com/31152763/?spm_id_from=333.999.0.0" },
    { title: "神么设计Lucas", href: "https://space.bilibili.com/3461576011025252/?spm_id_from=333.999.0.0" },
    { title: "碳基少年", href: "https://space.bilibili.com/294938732/?spm_id_from=333.999.0.0" },
    { title: "-陈殇-", href: "https://space.bilibili.com/451031842/?spm_id_from=333.999.0.0" },
    { title: "乃我白誫", href: "https://space.bilibili.com/34759641?spm_id_from=333.999.0.0" },
    { title: "节奏大师小虚", href: "https://api.xiaoheihe.cn/v3/bbs/app/api/web/share?link_id=131793215" },
  ]
